"""empty message

Revision ID: 948b485424d1
Revises: 
Create Date: 2017-04-12 00:51:29.961957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948b485424d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reputation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('domain_name', sa.String(length=40), nullable=True),
    sa.Column('rep', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reputation')
    # ### end Alembic commands ###
